"""
Audit report generation.

The claim this project makes is that a control mapping produced at detection time
is the artifact an auditor asks for. That claim is only worth making if the
artifact actually exists and can leave the system, so this renders an incident —
or a whole campaign — as a self-contained Markdown report.

What goes in is deliberately limited to what the pipeline actually determined.
No placeholder sections, no "TBD": a report with invented structure is worse than
a short one, because a reviewer cannot tell which parts were real.
"""

from datetime import UTC, datetime
from typing import Any


def _fmt_ts(value: Any) -> str:
    text = str(value or "").strip()
    if not text:
        return "unknown"
    return text.replace("T", " ").replace("Z", " UTC")


def _bullets(items: list[str], empty: str = "_None recorded._") -> str:
    items = [str(i).strip() for i in (items or []) if str(i).strip()]
    if not items:
        return empty
    return "\n".join(f"- {i}" for i in items)


def _generated_line() -> str:
    now = datetime.now(UTC).strftime("%Y-%m-%d %H:%M UTC")
    return f"_Generated by SENTRA on {now}. Every field below was produced by the detection pipeline; nothing is manually entered._"


def incident_report(incident: dict) -> str:
    """Render one incident as a Markdown audit record."""
    detection = incident.get("detection") or {}
    dash = incident.get("dashboard") or {}
    raw = incident.get("raw_event") or {}
    cis = incident.get("cis") or {}
    cvss = incident.get("cvss") or {}
    ai = incident.get("ai_analysis") or {}
    resp = incident.get("response") or {}
    attack = incident.get("mitre_attack") or {}
    campaign = incident.get("campaign") or {}

    event_id = incident.get("event_id", "unknown")
    primary = attack.get("primary") or {}

    lines: list[str] = []
    add = lines.append

    add(f"# Incident Record — {event_id}")
    add("")
    add(_generated_line())
    add("")

    # ── Summary table ────────────────────────────────────────────────────────
    add("## Summary")
    add("")
    add("| Field | Value |")
    add("| --- | --- |")
    add(f"| Incident ID | `{event_id}` |")
    add(f"| Detected at | {_fmt_ts(raw.get('timestamp') or dash.get('timestamp'))} |")
    add(f"| Verdict | **{str(detection.get('label', 'unknown')).upper()}** |")
    add(f"| Threat type | {str(detection.get('threat_type', 'unknown')).replace('_', ' ')} |")
    add(f"| Severity | **{str(detection.get('severity', 'unknown')).upper()}** |")
    add(f"| Detection confidence | {detection.get('confidence', 'n/a')} |")
    add(f"| CVSS 3.1 base score | **{cvss.get('base_score', 'n/a')}** ({cvss.get('severity', 'n/a')}) |")
    add(f"| CVSS vector | `{cvss.get('vector_string', 'n/a')}` |")
    add(f"| Response priority | {resp.get('priority', 'n/a')} |")
    if campaign:
        add(f"| Part of campaign | {campaign.get('campaign_id')} — {campaign.get('name')} |")
    add("")

    # ── Affected scope ───────────────────────────────────────────────────────
    add("## Affected Scope")
    add("")
    add("| Field | Value |")
    add("| --- | --- |")
    add(f"| Source address | `{dash.get('source_ip') or raw.get('source_ip') or 'unknown'}` |")
    add(f"| Destination | `{dash.get('destination_ip') or raw.get('destination_ip') or 'n/a'}` |")
    add(f"| Affected host | `{dash.get('affected_host') or raw.get('affected_host') or 'unknown'}` |")
    add(f"| Affected account | `{dash.get('affected_user') or raw.get('affected_user') or 'unattributed'}` |")
    add(f"| Log source | {dash.get('log_family') or raw.get('log_type') or 'unknown'} |")
    add("")

    # ── ATT&CK ───────────────────────────────────────────────────────────────
    if primary:
        add("## MITRE ATT&CK Classification")
        add("")
        add(f"**Primary technique:** [{primary.get('technique_id')}]({primary.get('url')}) — {primary.get('technique_name')}")
        add("")
        add(f"**Tactic:** {primary.get('tactic_name')} (`{primary.get('tactic_id')}`)")
        add("")
        add(f"**Kill chain stage:** {attack.get('kill_chain_stage')}")
        add("")
        others = [t for t in (attack.get("techniques") or []) if t.get("technique_id") != primary.get("technique_id")]
        if others:
            add("**Corroborating techniques:**")
            add("")
            add(_bullets([f"[{t['technique_id']}]({t['url']}) — {t['technique_name']} ({t['tactic_name']})" for t in others]))
            add("")

    # ── The control evidence: the reason this report exists ───────────────────
    add("## Control Mapping (Audit Evidence)")
    add("")
    if cis.get("benchmark_id"):
        match_type = cis.get("match_type", "")
        provenance = (
            "matched against the shipped benchmark catalog"
            if match_type == "catalog_retrieval"
            else "selected from the threat-class control mapping (no direct catalog match)"
        )
        add(f"**Control:** `{cis.get('benchmark_id')}` — {cis.get('title', 'untitled')}")
        add("")
        add(f"**Framework:** {cis.get('framework', 'CIS')} · _{provenance}_")
        add("")
        if cis.get("section"):
            add(f"**Section:** {cis.get('section')}")
            add("")
        if cis.get("description"):
            add("**Control requirement**")
            add("")
            add(f"> {str(cis['description']).strip()}")
            add("")
        if cis.get("rationale"):
            add("**Rationale**")
            add("")
            add(f"> {str(cis['rationale']).strip()}")
            add("")
        if cis.get("remediation"):
            add("**Remediation**")
            add("")
            add(f"> {str(cis['remediation']).strip()}")
            add("")
        if cis.get("audit_procedure"):
            add("**Audit procedure**")
            add("")
            add("```")
            add(str(cis["audit_procedure"]).strip())
            add("```")
            add("")
    else:
        add("_No control mapping was produced for this incident._")
        add("")

    # ── Analysis ─────────────────────────────────────────────────────────────
    add("## Analysis")
    add("")
    if ai.get("intent"):
        add(f"**Assessed intent:** {ai['intent']}")
        add("")
    if ai.get("narrative"):
        add(str(ai["narrative"]).strip())
        add("")
    impact = ai.get("impact") or {}
    if impact:
        add("**Assessed impact (CVSS dimensions)**")
        add("")
        add("| Confidentiality | Integrity | Availability |")
        add("| --- | --- | --- |")
        add(f"| {impact.get('confidentiality', 'n/a')} | {impact.get('integrity', 'n/a')} | {impact.get('availability', 'n/a')} |")
        add("")

    reasoning = detection.get("reasoning") or []
    if reasoning:
        add("**Detection reasoning**")
        add("")
        add(_bullets(reasoning))
        add("")
    engines = detection.get("triggered_engines") or []
    if engines:
        add(f"**Engines that contributed:** {', '.join(engines)}")
        add("")

    # ── Response ─────────────────────────────────────────────────────────────
    add("## Response")
    add("")
    add(f"**Priority:** {resp.get('priority', 'n/a')} — {resp.get('escalation', '')}")
    add("")
    plan = resp.get("containment_plan") or []
    if plan:
        add("**Containment plan**")
        add("")
        add("| Action | Execution | Blast radius |")
        add("| --- | --- | --- |")
        for step in plan:
            add(f"| {step.get('action')} | {step.get('execution')} | {step.get('blast_radius')} |")
        add("")
        gated = [s for s in plan if s.get("execution") == "requires_approval"]
        if gated:
            add(
                f"_{len(gated)} of {len(plan)} containment actions require analyst approval "
                "before execution because they can interrupt a live service._"
            )
            add("")
    if resp.get("recommended_actions"):
        add("**Recommended actions**")
        add("")
        add(_bullets(resp["recommended_actions"]))
        add("")

    add("---")
    add("")
    add(
        "_This record was generated automatically at detection time. The control "
        "mapping, severity score and containment plan are reproducible: re-running "
        "the pipeline over the same log produces the same record._"
    )

    return "\n".join(lines) + "\n"


def campaign_report(campaign: dict, incidents: list[dict]) -> str:
    """Render a campaign and its member incidents as one Markdown report."""
    lines: list[str] = []
    add = lines.append

    cid = campaign.get("campaign_id", "unknown")
    add(f"# Campaign Report — {cid}")
    add("")
    add(f"## {campaign.get('name', 'Unnamed campaign')}")
    add("")
    add(_generated_line())
    add("")

    add("| Field | Value |")
    add("| --- | --- |")
    add(f"| Campaign ID | `{cid}` |")
    add(f"| Severity | **{str(campaign.get('severity', 'unknown')).upper()}** |")
    add(f"| Correlated incidents | {campaign.get('incident_count', 0)} |")
    add(f"| Furthest stage reached | **{campaign.get('furthest_stage', 'unknown')}** |")
    add(f"| Lifecycle progression | {campaign.get('progression_pct', 0)}% |")
    add(f"| First observed | {_fmt_ts(campaign.get('first_seen'))} |")
    add(f"| Last observed | {_fmt_ts(campaign.get('last_seen'))} |")
    if campaign.get("escalated"):
        add(
            f"| Severity escalated | Yes — members peaked at "
            f"{campaign.get('member_max_severity')}, raised because the chain spans "
            f"{campaign.get('stages_reached')} stages |"
        )
    add("")

    if campaign.get("narrative"):
        add("## Assessment")
        add("")
        add(str(campaign["narrative"]).strip())
        add("")

    add("## Attack Chain")
    add("")
    chain = campaign.get("kill_chain") or []
    if chain:
        add("| # | Stage | Technique | First observed | Incident |")
        add("| --- | --- | --- | --- | --- |")
        for i, step in enumerate(chain, start=1):
            add(
                f"| {i} | {step.get('stage')} | `{step.get('technique')}` "
                f"{step.get('technique_name', '')} | {_fmt_ts(step.get('first_seen'))} | "
                f"`{step.get('event_id')}` |"
            )
        add("")
    else:
        add("_No mapped stages._")
        add("")

    add("## Correlation Basis")
    add("")
    add("These alerts were grouped because:")
    add("")
    add(_bullets(campaign.get("linked_by") or []))
    add("")

    add("## Scope")
    add("")
    add(f"**Source addresses involved:** {', '.join(f'`{a}`' for a in (campaign.get('actors') or [])) or 'none'}")
    add("")
    add(f"**Assets involved:** {', '.join(f'`{a}`' for a in (campaign.get('assets') or [])) or 'none'}")
    add("")
    if campaign.get("accounts"):
        add(f"**Accounts involved:** {', '.join(f'`{a}`' for a in campaign['accounts'])}")
        add("")
    if campaign.get("techniques"):
        add(f"**ATT&CK techniques observed:** {', '.join(f'`{t}`' for t in campaign['techniques'])}")
        add("")

    # Member incidents, each with its control mapping — the audit trail.
    by_id = {i.get("event_id"): i for i in incidents}
    members = [by_id[i] for i in (campaign.get("incident_ids") or []) if i in by_id]

    add("## Member Incidents")
    add("")
    if members:
        add("| Incident | Time | Threat | Severity | CVSS | Control |")
        add("| --- | --- | --- | --- | --- | --- |")
        for m in members:
            d = m.get("detection") or {}
            c = m.get("cis") or {}
            v = m.get("cvss") or {}
            raw = m.get("raw_event") or {}
            add(
                f"| `{m.get('event_id')}` | {_fmt_ts(raw.get('timestamp'))} | "
                f"{str(d.get('threat_type', '')).replace('_', ' ')} | {d.get('severity', '')} | "
                f"{v.get('base_score', '')} | `{c.get('benchmark_id', '')}` |"
            )
        add("")
    else:
        add("_Member incidents were not available when this report was generated._")
        add("")

    add("---")
    add("")
    add(
        "_Correlation is deterministic: the same set of alerts always produces the "
        "same campaign grouping and the same chain ordering._"
    )

    return "\n".join(lines) + "\n"
