CREATE TABLE incidents (
    event_id TEXT PRIMARY KEY,
    timestamp TEXT,
    severity TEXT,
    threat_type TEXT,
    affected_user TEXT,
    affected_host TEXT,
    source_ip TEXT,
    status TEXT NOT NULL DEFAULT 'open',
    analyst_label TEXT,
    payload TEXT NOT NULL,
    CONSTRAINT incidents_status_check
        CHECK (status IN ('open', 'closed', 'investigating')),
    CONSTRAINT incidents_analyst_label_check
        CHECK (
            analyst_label IS NULL OR analyst_label IN (
                'true_positive', 'false_positive', 'false_negative', 'escalated'
            )
        )
);

CREATE TABLE analyst_feedback (
    feedback_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id TEXT NOT NULL,
    label TEXT NOT NULL,
    reason TEXT,
    analyst_notes TEXT,
    source_ip TEXT,
    threat_type TEXT,
    affected_user TEXT,
    created_at TEXT NOT NULL,
    CONSTRAINT analyst_feedback_incident_fk
        FOREIGN KEY (event_id) REFERENCES incidents(event_id) ON DELETE CASCADE,
    CONSTRAINT analyst_feedback_label_check
        CHECK (label IN ('true_positive', 'false_positive', 'false_negative', 'escalated'))
);

CREATE TABLE campaigns (
    campaign_id TEXT PRIMARY KEY,
    name TEXT,
    severity TEXT,
    incident_count INTEGER,
    furthest_stage TEXT,
    progression_pct INTEGER,
    first_seen TEXT,
    last_seen TEXT,
    payload TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    CONSTRAINT campaigns_progression_check
        CHECK (progression_pct IS NULL OR progression_pct BETWEEN 0 AND 100),
    CONSTRAINT campaigns_incident_count_check
        CHECK (incident_count IS NULL OR incident_count >= 0)
);

CREATE TABLE response_approvals (
    approval_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id TEXT NOT NULL,
    action TEXT NOT NULL,
    state TEXT NOT NULL DEFAULT 'pending',
    requested_at TEXT NOT NULL,
    decided_at TEXT,
    decided_by TEXT,
    note TEXT,
    CONSTRAINT response_approvals_incident_fk
        FOREIGN KEY (event_id) REFERENCES incidents(event_id) ON DELETE CASCADE,
    CONSTRAINT response_approvals_state_check
        CHECK (state IN ('pending', 'approved', 'rejected'))
);

CREATE TABLE determinations (
    subject_key TEXT PRIMARY KEY,
    determined_at TEXT NOT NULL
);
